#!/usr/bin/env bash

OLDIFS="$IFS"
IFS=$'\n'

for nemo in `bcs nemos --currency CLP -c nemo | tail -n +2`;
do
    fnemo="$nemo.csv"
    [[ -f $fnemo ]] || touch "$fnemo"

    date=`tail -n +2 "$fnemo" | tail -n 1 | cut -f1 -d,`
    if [[ -z $date ]]; then
        bcs daily  "$nemo" > "$fnemo"
    else
        # It's tail -n +(2 + 1),  skip header and first entry, because
        # first entry of input is equal to last in the file
        bcs daily --from "$date" "$nemo" | tail -n +3 >> "$fnemo"
    fi
done

IFS="$OLDIFS"

git add .
git commit -m "update: $(date --iso-8601)"
git push origin master
